project 'CustomCalculatorProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'CustomCalculatorProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomCalculatorProject
  #pod 'CustomCalculatorFramework', :path => '../CustomCalculatorFramework'
  pod 'CustomCalculatorFramework'

end
